### PR TITLE
Add Settings Route and fix CSS Layout issues

### PR DESCRIPTION
**Pull request by cjharkins**
This PR Adds route for settings in "footer" area.

Fixed some CSS layout issues that would become a hinderance later on, absolute positioning can cause wonky responsive behaviors later. Migrated layout to Flexbox.

### CODE REVIEW

**Comment by ganeshpatro321** [comment]
HI @cjharkins , Thanks for your interest in this project. The changes will be reviewed soon. It would be great if you could provide a screenshot of the UI after changes.

**Comment by cjharkins** [comment]
Screen Shot 2019-10-19 at 2 14 53 PM


UI is same, just the code that generates is streamlined

**Comment by ganeshpatro321** [comment]
Ohh cool!

**Comment by muskankhedia** [comment]
Thanks for your contribution and interest in the project. Please pull the latest code and fix the conflicts. Also, attach the screenshot of the app after resolving the conflicts.

**Comment by cjharkins** [comment]
Hey peoples! I'm making a right mess of these commits, closing this. The addition of the notification panel breaks the layout. I fixed the notification layout, but now am way too far in commit history it seems to pass the DCO scans. 

Will try to fix my branch and open new PR.

**Pull request closed without merging**
