### PR TITLE
CSS Fixes and Settings route pt2

### PR DESCRIPTION
**Pull request by cjharkins**
Hey everyone, sorry about that last mess.

This should pipe in smoothly.

Fixes:
- Migrate logic for Notification panel
- Fix positioning and emphasize animation for Notification
- Add settings route
- Simplify click handler for show/hide
- Migrate some files to .tsx

### CODE REVIEW

**Comment by cjharkins** [comment]
appScreen_20191020
appScreenNotification_20191020

**Comment by Harkishen-Singh** [comment]
@cjharkins thanks for showing your interest in the project. Could you please follow the [instructions](https://github.com/zairza-cetb/bench-routes-electron/pull/21/checks?check_run_id=267297702) to pass the DCO.?

will review asap. Thanks

**Comment by ganeshpatro321** [comment]
@cjharkins looks good, Just few things:
- Run `npm run lint` through the codebase, and check for any errors or warnings and resolve them.
- Can you change the icon beside the settings button in the sidebar.

**Comment by cjharkins** [comment]
@ganeshpatro321 @Harkishen-Singh I'm following the instructions for the DCO, and it isn't giving me the desired result. 

I wish all the work I've done was not in vain, however, I don't feel as though I can continue to commit time to fixing this trivial issue. 

If you have a fix for me, I will be happy to try it. If not, thank you for the opportunity to contribute! I hope the project goes well :)

**Comment by ganeshpatro321** [comment]
Hey @cjharkins . I have updated the minor changes I had asked for and have created an updated PR. Dont worry, your commits are safe ;D Thanks for your contribution, and hope to see more contribution from you. Thanks

**Comment by ganeshpatro321** [comment]
Commits merged in PR #24

**Pull request closed without merging**
